python train_fairGNN.py \
        --seed=42 \
        --epochs=1800 \
        --model=GCN \
        --sens_number=200 \
        --dataset=pokec_n \
        --num-hidden=128 \
        --acc=0.68 \
        --roc=0.730 \
        --alpha=50 \
        --beta=1